name: Deploy

on:
  push:
    branches: [ "matrix" ]

env:
  PROJECT_NAME: ${{ github.repository }}
  PROJECT_VERSION: ${{ github.sha }}
  WORKFLOW_ENVIRONMENT: staging
  KUBE_CONFIG: ${{ secrets.STAGING_KUBE_CONFIG }}
  K8S_NAMESPACE: ${{ vars.STAGING_K8S_NAMESPACE }}
  DO_CR_DOCKERCONFIGJSON: ${{ secrets.DO_CR_DOCKERCONFIGJSON }}
  DO_CR_URI_REPOSITORY: ${{ vars.DO_CR_URI_REPOSITORY }}
  AWS_SES_EMAIL: ${{ vars.STAGING_AWS_SES_EMAIL }}
  OAUTH_WEBAPP_HOST: ${{ vars.STAGING_OAUTH_WEBAPP_HOST }}
  IMAGE_TAG: ${{ github.repository }}:${{ github.sha }}
  RELEASE_IMAGE_TAG: ${{ github.repository }}:latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build --target builder -t $IMAGE_TAG .

    - name: Copy dist folder
      run: |
        docker cp $(docker create --name builder $IMAGE_TAG):/root/code/dist .

    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.com'
    - run: npm publish --provenance --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
