name: Deploy

on:
  push:
    branches: [ "matrix" ]
    paths:
        - 'package.json'
        - 'yarn.lock'
        - '.npmrc'
        - '.npmignore'
        - 'tsconfig.json'
        - '.babelrc'
        - 'src/**'

env:
  IMAGE_TAG: ${{ github.repository }}:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build --target exporter -t $IMAGE_TAG .

    - name: Publish package
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: docker run -e NODE_AUTH_TOKEN=$NODE_AUTH_TOKEN $IMAGE_TAG npm publish --provenance --access public
